course = "  Python Programming"
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.rstrip())
print(course.find("pro"))
print(course.rstrip())
print(course.replace("Programming", "Automation"))
print("Pro" in course)
print("swift" not in course)
